name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Barani
        run: 
         echo "Hello World 1"

      - name: Barani_2
        run: 
         echo "Hello World 2"

      - name: Barani_3
        run: 
         echo "Hello World 3"


      - name: Barani_2
        run: 
         echo "Hello World 4"
    

         
